---
- name: Deploy placement app
  hosts: all
  tasks:
    - name: delete previous backend yml
      shell: kubectl delete -f /home/aryan/Desktop/Placement/Spe_Major_deploy/kubernetes/backend.yml

    - name: delete previous frontend yml
      shell: kubectl delete -f /home/aryan/Desktop/Placement/Spe_Major_deploy/kubernetes/frontend.yml

    - name: apply backend
      # become: true
      shell: kubectl apply -f /home/aryan/Desktop/Placement/Spe_Major_deploy/kubernetes/backend.yml

    - name: apply frontend
      # become: true
      shell: kubectl apply -f /home/aryan/Desktop/Placement/Spe_Major_deploy/kubernetes/frontend.yml
