---
- name: Deploy placement app
  hosts: all
  tasks:
   
    - name: Copy backend deployment file
        copy:
          src: ./kubernetes/backend.yml
          dest: ./
      
    - name: Copy frontend deployment files
        copy:
          src: ./kubernetes/frontend.yml
          dest: ./

    - name: apply backend
      become: true
      shell: kubectl apply -f ./backend.yml

    - name: apply frontend
      become: true
      shell: kubectl apply -f ./frontend.yml
